export const SUBMIT_REPO_LINK = 'SUBMIT_REPO_LINK';
export const SET_FILTER = 'SET_FILTER';
export const CLOSE_ISSUE_VIEWER = 'CLOSE_ISSUE_VIEWER';
export const LOAD_ISSUES = 'LOAD_ISSUES';
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';